# Numpy 101

first we import the numpy module into our program. Time is also imported so we can test numpy's legendary effiecency against vannila 
python

In [1]:
import time
import numpy as np

now we use numpy.random.random(10000000) to genereate a big array of floats between 0 and 1.

In [2]:
x = np.random.random(100000000)

now we calculate the mean and time the result. we could replace all our time code with just %%timeit at the begining of the code blocks but this is easier to read.

In [5]:
start = time.time()
sum(x) / len(x)
print(time.time() - start)

12.192470073699951


In [6]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.06198477745056152


## now lets dive in to creating ndarrays

in numpy we can call this array a rank 1 array because it uses only one dimension

In [7]:
x = np.array([1,2,3,4,5])

numpy allows you to see what type of elements are in a array with .dtype

In [10]:
print(x)
print(type(x))
x.dtype

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int64')

we can also use .shape to return a tuple of n positive integers that shows how many dimensions are in array and there length

In [11]:
x.shape

(5,)

now we'll make a two dimensional (rank 2)array to use for more numpy testing.

In [12]:
y = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(y)
print(type(y))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [13]:
y.shape

(4, 3)

.size tells us the total amount of varaibles in all dimensions of our ndarray.

In [14]:
y.size

12

In [15]:
x = np.array(['hello', 'world'])
print(x)

['hello' 'world']


In [16]:
print("shape:", x.shape)
print("type:", type(x))
print("dtype:", x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


what happens when we mix data types?

In [17]:
x = np.array([1, 2, 3.5])
print(x, x.dtype)

[1.  2.  3.5] float64


as you can see above they are all 'upcast' the variables

In [19]:
x = np.array([1,2,3.5], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


as you see above we can also manually select the kind of variables we want our ndarray to use when we create it with the optional argument 'dtype'

numpy even allows you to easily save arrays to files for later use

In [20]:
x = np.array([1,2,4.5])
np.save('my_array_name', x)

now we can load it back in

In [21]:
y = np.load('my_array_name.npy')
print(y)

[1.  2.  4.5]


## creating arrays from nothing with numpy functions

create a array of zeros with .zeros. (this would default to float64 if we didn't specify dtype)

In [26]:
x = np.zeros((3, 4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


we can also do the dame for a ones array with .ones

In [27]:
x = np.ones((4, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


we can do this for any cosnant element we want with .full

In [28]:
x = np.full((4, 3), 5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [29]:
print(x.dtype)

int64


we can create linear algebra identity matrix (rank 2 arrays) with .eye

In [30]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


we can also create a diagonal matrix (still rank 2 but with only values on the main diagonal

In [32]:
x = np.diag([10, 20, 30, 50])
print("x = \n", x)

x = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


generate arrays with specific numerical ranges. arange uses start stop and step to create arrays

In [33]:
x = np.arange(10)#defaults to stop argument
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
x = np.arange(4, 10)#start and stop
print(x)

[4 5 6 7 8 9]


In [36]:
x = np.arange(1, 14, 3)#start stop step
print(x)

[ 1  4  7 10 13]


### .linspace takes start stop and n for non integer based steps

In [37]:
x = np.linspace(0, 25, 10)#start stop steps
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


we can remove the last element with the arg endpoint

In [38]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


We can reshape any of our numpy arrays to be two dimensional with np.reshape

first we will turn our array back to normal numbers to make it easier to manipulate

In [40]:
x = np.arange(20)
print(x)

In [42]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


the second argument of reshape must contain values that match the number of elements in the array i.e. 20 is divisiable by 4 and 5

we can shorten lines 40-42 into one line with numpy's methods

In [43]:
x = np.arange(25).reshape((5,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


notice above we dn't need to pass the array into resphape

this also works with other arrays like linspace

In [45]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


create an array of a given length

In [46]:
x = np.random.random((3, 3))
print(x)

[[0.17515248 0.95344181 0.74022252]
 [0.02814212 0.8826069  0.00539715]
 [0.3711952  0.04438561 0.56416672]]


In [47]:
x = np.random.randint(4, 15, (3, 2))#inclusive lowerbound, exclusive upper bound, and shape

In [48]:
x = np.random.normal(0, 0.1, size=(1000, 1000))#mean, standard deviation, shape
print(x)

[[-0.1846311   0.06383114 -0.1215044  ...  0.06552078 -0.0126139
  -0.16573534]
 [-0.0504905   0.19883304  0.07369813 ...  0.12047595 -0.17081959
   0.07420166]
 [-0.00286885 -0.08850031 -0.15869347 ... -0.13531531 -0.08176501
  -0.21727883]
 ...
 [-0.19512847 -0.01748074  0.10230614 ...  0.0680487   0.02863882
  -0.02619155]
 [ 0.03154106  0.09909325  0.19394429 ...  0.0086005  -0.18121215
   0.07344543]
 [-0.08163119  0.10355523 -0.04033972 ... -0.06804157 -0.08932665
  -0.1108985 ]]


In [49]:
print('mean:', x.mean())
print('std:', x.std())
print('max:', x.max())
print('min:', x.min())
print('# positive:', (x > 0).sum())
print('# negative:', (x < 0).sum())

mean: 0.0001506362792929358
std: 0.10007896119808517
max: 0.4763980671031341
min: -0.5140772382686051
# positive: 500668
# negative: 499332


## accessing, deleting, and inserting into ndarray

elements are mutable in ndarray

In [50]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [51]:
print('1st element:', x[0])
print('second element:', x[1])

1st element: 1
second element: 2


we can also get elems with neg indecies

In [53]:
print('1st element', x[-5])
print('5th element', x[-1])

1st element 1
5th element 5


we can access and modify a element the same way


In [54]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


we can also do this with rank 2 arrays using two indecies

In [55]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print('e at 0,1:', x[0][1])
print('e at 2,0:', x[2][0])

e at 0,1: 2
e at 2,0: 7


we can use this to update elements as well

In [57]:
x[2][1] = 20
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 20  9]]


### adding and deleting elements

In [60]:
x = np.array([1,2,3,4,5])# a rank 1 array
print(x)

x = np.delete(x, [0,4])
#deleting elements at poition zero and four(in this case 1 and 5)
print(x)

[1 2 3 4 5]
[2 3 4]


In [64]:
x = np.arange(1,10).reshape(3,3)
print(x)

w = np.delete(x, 0, axis=0)#delete first row
print("\n w: \n", w)

c = np.delete(x, [0,2], axis=1)
print('\n c:\n', c) #delete first and third elem of each row

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 w: 
 [[4 5 6]
 [7 8 9]]

 c:
 [[2]
 [5]
 [8]]


### appending elements

In [65]:
x = np.array([1,2,3,4,5])# a rank 1 array
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


append multiple elements

In [66]:
x = np.append(x, [7,8])
print(x)

[1 2 3 4 5 6 7 8]


this can of course be used on rank 2 arrays

In [68]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### append a row

In [69]:
c = np.append(x, [[10,11,12]], axis=0)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##### append a column

In [71]:
v = np.append(x, [[10], [11], [12]], axis=1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


###### inserting elements

In [83]:
x = np.array([1,2,3,7,8])# a rank 1 array
print(x)

[1 2 3 7 8]


In [84]:
x = np.insert(x, 3,[5,6])
print(x)

[1 2 3 5 6 7 8]


now with a rank 2 array

In [86]:
y = np.array([[1,2,3],[7,8,9]])
print(y)

[[1 2 3]
 [7 8 9]]


In [89]:
z = np.insert(y, 1, [4,5,6], axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


insert a column

In [91]:
z = np.insert(y, 1, 5, axis=1)
print(z)

[[1 5 2 3]
 [7 5 8 9]]


##### stacking arrays

In [93]:
x = np.array([1,2])
print(x)

y = np.array([[3,4], [5,6]])
print(y)

[1 2]
[[3 4]
 [5 6]]


vertical stacking:

In [95]:
z = np.vstack((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


horizontal stacking:


In [97]:
w = np.hstack((y, x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


##### we can also slice of course


In [99]:
x = np.arange(1,21).reshape(4,5)
print(x[0:5])
print(x[:4])
z = x[1:4, 2:5]
print("z:",z)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
z: [[ 8  9 10]
 [13 14 15]
 [18 19 20]]


first is row then coloumn


In [101]:
z = x[:3,2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [103]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


z is just a view of x. changing z also changes x and vise versa


In [106]:
z[2,0] = 555
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12 555  14  15]
 [ 16  17  18  19  20]]


above arrays are just based on one array x. below we actually copy 

In [109]:
x = np.arange(20).reshape(4,5)
z = x[1:,2:].copy()
print(x)
z[2,2] = 255
print(z)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[  7   8   9]
 [ 12  13  14]
 [ 17  18 255]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


as you can see z's array has changed but not x's

### extract diagonals

In [111]:
z = np.diag(x)
print(x)
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  6 12 18]


k is a optional param to move the diagonal you want to slice up or down from the central diagonal

In [112]:
z = np.diag(x, k=1)
print(z)

[ 1  7 13 19]


grabbing only the unique elements from

In [113]:
z = np.unique(x)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Boolean indexing, set ops, and sorting

In [114]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


values greater then 10

In [115]:
print(x[x >10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


values less then 7


In [116]:
print(x[x < 7])

[0 1 2 3 4 5 6]


greater then 5 and less then 17

In [117]:
print(x[(x > 5) & (x  < 17)])

[ 6  7  8  9 10 11 12 13 14 15 16]


assigning elements that meet condition to a value

In [120]:
x[(x >5) & (x <13)] = 0000
print(x)

[[ 0  1  2  3  4]
 [ 5  0  0  0  0]
 [ 0  0  0 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


set operations are useful to compare dif arrays

In [124]:
x = np.arange(1,6)

In [125]:
print(x)

[1 2 3 4 5]


In [126]:
y = np.array([6,7,2,8,4])
print(y)

[6 7 2 8 4]


interection of two arrays

In [130]:
print(np.intersect1d(x,y))

[2 4]


elements in x and not in y

In [132]:
print(np.setdiff1d(x,y))

[1 3 5]


union of sets

In [134]:
print(np.union1d(x, y))

[1 2 3 4 5 6 7 8]


### sorting

In [135]:
x = np.random.randint(1, 11, size=(10,))
print(x)


[ 8  7  6  4  8 10  1  5  5  1]


first way to sort (without changing the orig array)

In [136]:
print(np.sort(x))
print(x)

[ 1  1  4  5  5  6  7  8  8 10]
[ 8  7  6  4  8 10  1  5  5  1]


sort only unique


In [137]:
print(np.sort(np.unique(x)))

[ 1  4  5  6  7  8 10]


second sort way (change orig array)

In [138]:
print(x)

[ 8  7  6  4  8 10  1  5  5  1]


In [140]:
x.sort()
print(x)

[ 1  1  4  5  5  6  7  8  8 10]


sorting rank 2 arrays

In [142]:
x = np.random.randint(1, 11, size=(5,5))
print(x)


[[ 9  8  4  1  8]
 [ 6  9  7  1  8]
 [ 1  2  4  9  1]
 [ 1  9  5 10  6]
 [10  1  7  2  4]]


sort by rows

In [147]:
print(np.sort(x, axis=0))

[[ 1  1  4  1  1]
 [ 1  2  4  1  4]
 [ 6  8  5  2  6]
 [ 9  9  7  9  8]
 [10  9  7 10  8]]


sort by coloumns

In [148]:
print(np.sort(x, axis=1))

[[ 1  4  8  8  9]
 [ 1  6  7  8  9]
 [ 1  1  2  4  9]
 [ 1  5  6  9 10]
 [ 1  2  4  7 10]]


### artimetic operations and broadcasting on ndarray

element wise operations

In [151]:
x = np.arange(1,5)
y = np.arange(5,9)
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [152]:
print(x + y)

[ 6  8 10 12]


In [153]:
print(np.add(x, y))

[ 6  8 10 12]


In [155]:
print(x - y)

print(np.subtract(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [156]:
print(x * y)
print(np.multiply(x,y))


[ 5 12 21 32]
[ 5 12 21 32]


In [165]:
print(x / y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


square root

In [166]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


exponetional

In [168]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


power of

In [169]:
print(np.power(x, 2))

[[ 1  4]
 [ 9 16]]


broadcasting
(how numpy handles operations between arrays of dif length)

In [163]:
X = x.reshape(2,2)
Y = y.reshape(2,2)
print(X)
print(Y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [164]:
print(X + Y)

[[ 6  8]
 [10 12]]


statiscal functions

In [171]:
print('avg of all:', X.mean())

avg of all: 2.5


In [172]:
print("avg coloums", X.mean(axis=0))
print("avg rows", X.mean(axis=1))

avg coloums [2. 3.]
avg rows [1.5 3.5]


In [174]:
print("sum of all", X.sum())
print("sum of rows", X.sum(axis=1))

sum of all 10
sum of rows [3 7]


In [175]:
X.std()

1.118033988749895

In [176]:
np.median(X)

2.5

In [177]:
X.max()

4

In [178]:
X.min()

1

add/multiply/etc number to every nmber in array

In [180]:
print(X)

[[1 2]
 [3 4]]


In [181]:
print(X * 3)

[[ 3  6]
 [ 9 12]]


In [182]:
y = np.arange(9).reshape(3,3)
print(y)
x = np.arange(3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [183]:
print(y + x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]



broadcasting only works if the array shaps fit i.e. 1,3 and 3,3 but not 1,4 and 3,3